In [221]:
import pandas as pd
import seaborn as se
import numpy as np
import re 
import sklearn as sk
import matplotlib

In [2]:
# 读取数据
data = pd.read_excel("newdata0309.xlsx")

In [23]:
# 查看数据
data.head()

,1,2,3,4,5,6,7,8,9,10,...,18,19,20,21,22,23,24,25,Unnamed: 25,Unnamed: 26
0,610002,1144610000591607,2016610002844650002702,P610000000163,商务精英卡,T,7,2017-10-20,2016-10-20,PA,...,何凌,2016610000602251622,610104197405207314,M,1974-05-20 00:00:00,M,48565,任春莉,NaN,NaN
1,610002,1144610000592087,2016610002844650002731,P610000000163,商务精英卡,T,7,2017-10-20,2016-10-20,PA,...,张有利,2016610002600002134,61011119590404151X,M,1959-04-04 00:00:00,M,36852,梅利娜,NaN,NaN
2,610002,1144610000592089,2016610002844650002757,P610000000163,商务精英卡,T,7,2017-10-20,2016-10-20,PA,...,杨亚利,2016610002600002145,610111195805131544,F,1958-05-13 00:00:00,M,36852,梅利娜,NaN,NaN
3,610002,1144610000609818,2016610002844650003112,P610000000163,商务精英卡,T,7,2017-11-03,2016-11-03,PA,...,王振武,2011610000601004787,610629197607290034,M,1976-07-29 00:00:00,M,88363,郎红,NaN,NaN
4,610002,1144610000611761,2016610002844650003206,P610000000163,商务精英卡,T,7,2017-11-07,2016-11-07,PA,...,王翠贤,2007610002000016342,610121196407135029,F,1964-07-13 00:00:00,M,23373,王翠贤,NaN,NaN

In [206]:
drop_data = data.drop([1,2,5,3,19,7,10,14,'Unnamed: 25','Unnamed: 26'],axis = 1)

In [207]:
drop_data[drop_data[15]!=drop_data[20]]

,4,6,8,9,11,12,13,15,16,17,18,20,21,22,23,24,25
22,P610000000163,T,2018-05-17,2017-05-17,360.0,2481000,冯冠华,#,M,1899-12-31 00:00:00.000,冯以茉,610104201606063424,F,2016-06-06 00:00:00,P,36852,梅利娜
24,P610000000376,T,2018-05-25,2017-05-25,100.0,694500,党鹏辉,610121197609082214,M,1976-09-08 00:00:00,党卓悦,61012120001228220X,F,2000-12-28 00:00:00,C,41570,张密
38,P610000000387,T,2018-06-19,2017-06-19,110.0,110000,孔德强,610104198108074433,M,1981-08-07 00:00:00,孔紫涵,610104200810264421,F,2008-10-26 00:00:00,C,88131,潘西琴
39,P610000000387,T,2018-06-19,2017-06-19,110.0,110000,张鹏,61010319850522163X,M,1985-05-22 00:00:00,张舒尧,610104201305234445,F,2013-05-23 00:00:00,C,88131,潘西琴
40,P610000000374,T,2018-06-27,2017-06-27,50.0,41000,李新华,620302197606120821,F,1976-06-12 00:00:00,马劭薇,610113200204281623,F,2002-04-28 00:00:00,C,34222,李亚琪
41,P610000000387,T,2018-06-28,2017-06-28,110.0,110000,张红艳,622827199006114925,F,1990-06-11 00:00:00,赵子豪,621027201211190316,M,2012-11-19 00:00:00,C,37129,彭玉霞
43,P610000000387,T,2018-06-30,2017-06-30,110.0,110000,杨蕊娟,610121197002168206,F,1970-02-16 00:00:00,陈嘉怡,610121199901088209,F,1999-01-08 00:00:00,C,89365,杨蕊娟
44,P610000000387,T,2018-07-04,2017-07-04,110.0,110000,李强,610526198102234010,M,1981-02-23 00:00:00,李泽鑫,610526200607153435,M,2006-07-15 00:00:00,C,47867,潘小勇
46,P610000000373,T,2018-07-06,2017-07-06,360.0,129000,杨斌娟,610423198202132025,F,1982-02-13 00:00:00,康梦熙,61010320120507322X,F,2012-05-07 00:00:00,C,88670,董君
49,P610000000387,T,2018-07-08,2017-07-08,110.0,110000,陈斐,610103198212120827,F,1982-12-12 00:00:00,武辰浩宇,610103201208063633,M,2012-08-06 00:00:00,C,88019,赵艳丽
50,P610000000387,T,2018-07-08,2017-07-08,110.0,110000,戴志龙,610121197802030037,M,1978-02-03 00:00:00,戴昱莹,61011620140818014X,F,2014-08-18 00:00:00,C,89531,代志军
51,P610000000387,T,2018-07-08,2017-07-08,110.0,110000,罗萍,612133197608057524,F,1976-08-05 00:00:00,支近钰,61011320140613225X,M,2014-06-13 00:00:00,C,56991,王水云
52,P610000000387,T,2018-07-09,2017-07-09,110.0,110000,李金洋,610103198402051228,F,1984-02-05 00:00:00,宁奎杰,610113201501240515,M,2015-01-24 00:00:00,C,28035,刘赟
54,P610000000387,T,2018-07-09,2017-07-09,110.0,110000,梁彬,610103198512122410,M,1985-12-12 00:00:00,梁智鑫,610103201411114619,M,2014-11-11 00:00:00,C,88131,潘西琴
55,P610000000373,T,2018-07-10,2017-07-10,360.0,129000,黎艳红,36031119811028052X,F,1981-10-28 00:00:00,张悦晨,610116201108311080,F,2011-08-31 00:00:00,C,47867,潘小勇
57,P610000000387,T,2018-07-10,2017-07-10,110.0,110000,刘靖,610104197803045146,F,1978-03-04 00:00:00,柴畑羽,610104200507195128,F,2005-07-19 00:00:00,C,32064,苏华
58,P610000000387,T,2018-07-11,2017-07-11,110.0,110000,严枫,610424197104222328,F,1971-04-22 00:00:00,王贺仟,610424200105122323,F,2001-05-12 00:00:00,C,57026,严枫
59,P610000000387,T,2018-07-11,2017-07-11,110.0,110000,王艳兰,141124198209010045,F,1982-09-01 00:00:00,张瑞锦,610125201203276224,F,2012-03-27 00:00:00,C,44500,王雅君
60,P610000000387,T,2018-07-11,2017-07-11,110.0,110000,徐荣荣,610424197105172326,F,1971-05-17 00:00:00,韩嘉斌,610424200105172670,M,2001-05-17 00:00:00,C,57026,严枫
61,P610000000387,T,2018-07-12,2017-07-12,110.0,110000,高攀,610104198309035115,M,1983-09-03 00:00:00,高紫珊,610104201305225127,F,2013-05-22 00:00:00,C,32064,苏华
62,P610000000387,T,2018-07-12,2017-07-12,110.0,110000,高攀,610104198309035115,M,1983-09-03 00:00:00,高晨耀,610104200705155119,M,2007-05-15 00:00:00,C,32064,苏华
64,P610000000387,T,2018-07-13,2017-07-13,110.0,110000,张超,610104197612215261,F,1976-12-21 00:00:00,计禹同,610104200907170018,M,2009-07-17 00:00:00,C,88356,李格萍
90,P610000000387,T,2018-06-18,2017-06-18,110.0,110000,何伟,610104197009117317,M,1970-09-11 00:00:00,何依泽,610103199704140415,M,1997-04-14 00:00:00,C,37823,强小娟
91,P610000000387,T,2018-06-19,2017-06-19,110.0,110000,马姝,610121197412054009,F,1974-12-05 00:00:00,刘祎鑫,610111200704190012,M,2007-04-19 00:00:00,C,37129,彭玉霞
92,P610000000387,T,2018-06-20,2017-06-20,110.0,110000,黄东红,612731197808283016,M,1978-08-28 00:00:00,郝黄帅,610111200807182015,M,2008-07-18 00:00:00,C,40706,王路涵
94,P610000000387,T,2018-06-26,2017-06-26,110.0,110000,李新华,620302197606120821,F,1976-06-12 00:00:00,马劭薇,610113200204281623,F,2002-04-28 00:00:00,C,34222,李亚琪
95,P610000000387,T,2018-06-28,2017-06-28,110.0,110000,黄宗金,612525198405014221,F,1984-05-01 00:00:00,程清文,611024200808245919,M,2008-08-24 00:00:00,C,56992,程长爱
97,P610100000139,T,2018-07-05,2017-07-05,360.0,129000,刘洁,#,M,1899-12-31 00:00:00.000,马瑜阳,610103201311214313,M,2013-11-21 00:00:00,P,89006,胡兰英
98,P610000000387,T,2018-07-05,2017-07-05,110.0,110000,候君,610111198407080052,M,1984-07-08 00:00:00,候雨璐,610113201504010926,F,2015-04-01 00:00:00,C,28035,刘赟
99,P610000000373,T,2018-07-06,2017-07-06,360.0,129000,刘利,420984197612155633,M,1976-12-15 00:00:00,刘一衡,61011320040406042X,F,2004-04-06 00:00:00,C,32064,苏华
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
642036,P610000000409,K,NaT,2018-09-07,100.0,70000,周增杰,612727198903202122,F,1989-03-20 00:00:00,周玥如,610826201312317827,F,2013-12-31 00:00:00,C,88001214,王园园
642037,P610000000409,K,NaT,2018-09-07,100.0,70000,周东利,612727198611282124,F,1986-11-28 00:00:00,马瑜蔓,610802201507090625,F,2015-07-09 00:00:00,C,88001214,王园园
642038,P610000000409,K,NaT,2018-09-07,100.0,70000,郑文,612728198608221044,F,1986-08-22 00:00:00,艾帅宇,610802201312167215,M,2013-12-16 00:00:00,C,88001214,王园园
642039,P610000000409,K,NaT,2018-09-07,100.0,70000,崔玉冰,612732198606140034,M,1986-06-14 00:00:00,崔梦璐,610831201411180046,F,2014-11-18 00:00:00,C,88800059,王燕娥
642040,P610000000394,K,NaT,2018-09-07,100.0,100000,王新艳,612724197706110428,F,1977-06-11 00:00:00,曹智阳,610802201412080619,M,2014-12-08 00:00:00,C,88000741,呼皓
642041,P610000000409,K,NaT,2018-09-08,100.0,70000,高鹏飞,61272819850206081X,M,1985-02-06 00:00:00,高旭阳,610827200908200816,M,2009-08-20 00:00:00,C,88001197,苗坤
642042,P610000000409,K,NaT,2018-09-08,100.0,70000,张爱玲,612724199210152121,F,1992-10-15 00:00:00,王宇博,610823201401086312,M,2014-01-08 00:00:00,C,88000921,高江娟
642043,P610000000409,K,NaT,2018-09-08,100.0,70000,李艳霞,612729198508191526,F,1985-08-19 00:00:00,贺锦轩,610828201309281512,M,2013-09-28 00:00:00,C,88000921,高江娟
642044,P610000000405,K,NaT,2018-09-08,360.0,2481000,张文阳,612732199212270332,NaN,1900-01-01 00:00:00,曹成兰,612732196604150344,F,1966-04-15 00:00:00,x,88000001,秦志强
642045,P610000000394,K,NaT,2018-09-09,100.0,100000,田天,612701199008252626,F,1990-08-25 00:00:00,冯嘉怡,610802201309163221,F,2013-09-16 00:00:00,C,88800023,郝静
642046,P610000000394,K,NaT,2018-09-10,100.0,100000,袁缘,500227198905310421,F,1989-05-31 00:00:00,付永恩,610802201508111424,F,2015-08-11 00:00:00,C,88000516,赵桃
642047,P610000000394,K,NaT,2018-09-10,100.0,100000,任丽,612731197502070229,F,1975-02-07 00:00:00,陈嘉乐,61083020051217041X,M,2005-12-17 00:00:00,C,88000020,刘利利
642048,P610000000406,K,NaT,2018-09-11,360.0,2481000,王鹏军,612701198810231211,NaN,1900-01-01 00:00:00,徐慧,612701199002031427,F,1990-02-03 00:00:00,x,88000036,王鹏浩
642049,P610000000405,K,NaT,2018-09-12,360.0,2481000,侯旭峰,612701199004272216,NaN,1900-01-01 00:00:00,侯岱,612701196502202217,M,1965-02-20 00:00:00,x,88001039,张娜娜
642050,P610000000394,K,NaT,2018-09-12,100.0,100000,李斌,612732198308253911,M,1983-08-25 00:00:00,李文茉,610831201502074142,F,2015-02-07 00:00:00,C,88000077,曹小婧
642051,P610000000409,K,NaT,2018-09-12,100.0,70000,强艳红,612729198105162122,F,1981-05-16 00:00:00,薛子恒,61082820040703211X,M,2004-07-03 00:00:00,C,88001066,李莉
642052,P610000000207,K,NaT,2018-09-13,360.0,2481000,孙毅,612724198511291876,NaN,1900-01-01 00:00:00,杜改霞,612728198609012105,F,1986-09-01 00:00:00,x,88001134,高伟
642053,P610000000394,K,NaT,2018-09-14,100.0,100000,寇福剑,612701198509212038,M,1985-09-21 00:00:00,寇泽睿,610802201107132013,M,2011-07-13 00:00:00,C,88000100,高锦江
642054,P610000000394,K,NaT,2018-09-15,100.0,100000,白李鹏,612729199001244814,M,1990-01-24 00:00:00,白锦轩,610802201411061459,M,2014-11-06 00:00:00,C,88000009,马建军
642055,P610000000207,K,NaT,2018-09-15,360.0,2481000,张宝荣,612729197801251212,NaN,1900-01-01 00:00:00,郭艳娥,61272919780318122X,F,1978-03-18 00:00:00,x,88000840,郭艳娥
642056,P610000000394,K,NaT,2018-09-15,100.0,100000,牛水清,371121197801011257,M,1978-01-01 00:00:00,牛梓儒,371121200908141232,M,2009-08-14 00:00:00,C,88000179,韩梅
642057,P610000000406,K,NaT,2018-09-15,360.0,2481000,贺凌云,61272919900505361X,NaN,1900-01-01 00:00:00,贺录光,612729196009183610,M,1960-09-18 00:00:00,x,88001039,张娜娜
642058,P610000000394,K,NaT,2018-09-15,100.0,100000,常瑞,612701199110030069,F,1991-10-03 00:00:00,李一诺,610802201311071430,M,2013-11-07 00:00:00,C,88000238,张艳艳
642059,P610000000408,K,NaT,2018-09-16,50.0,35000,王晶,612701199008250620,F,1990-08-25 00:00:00,周子涵,610802201209110640,F,2012-09-11 00:00:00,C,88800105,封静
642060,P610000000408,K,NaT,2018-09-18,50.0,35000,张蓉蓉,610622199103261728,F,1991-03-26 00:00:00,任婉妮,610828201405226329,F,2014-05-22 00:00:00,C,88001180,李安安
642061,P610000000394,K,NaT,2018-09-20,100.0,100000,杨凯,612701199304251812,M,1993-04-25 00:00:00,杨岱仪,610802201804021829,F,2018-04-02 00:00:00,C,88000238,张艳艳
642062,P610000000406,K,NaT,2018-09-20,360.0,2481000,薛梅,612701198002070624,NaN,1900-01-01 00:00:00,张新颖,612701200301280701,F,2003-01-28 00:00:00,x,88000038,马艳飞
642064,P610000000394,K,NaT,2018-09-24,100.0,100000,刘菁,612728198603283027,F,1986-03-28 00:00:00,折予晞,610802201412037426,F,2014-12-03 00:00:00,C,88800023,郝静
642065,P610000000394,K,NaT,2018-09-26,100.0,100000,连小成,612724198506090914,M,1985-06-09 00:00:00,连志乾,610802201507298012,M,2015-07-29 00:00:00,C,88000020,刘利利
642068,P610000000394,K,NaT,2018-09-28,100.0,100000,张艳艳,612729198705086020,F,1987-05-08 00:00:00,张亦彤,610828200912106028,F,2009-12-10 00:00:00,C,88000009,马建军

[4, 6, 8, 9, 11, 12, 13, 15, 16, 17, 18, 20, 21, 22, 23, 24, 25]


['产品'，'TOrK','到期时间','投保时间','投保金额','保额','投保人姓名','投保人ID','投保人性别','投保人生日','受益人姓名','受益人ID','受益人性别','受益人生日','受益人投保人关系','客户经理ID','客户经理姓名']

'TOrK' T--> teminal K--> keep

In [208]:
drop_data.columns = ['Product','TOrK','T_time','S_time','Payment','Reward','A_Name','A_ID','A_gender','A_BD','B_Name','B_ID','B_gender','B_BD','A_B_Relation_Ship','S_ID','S_Name']

In [209]:
ReDrop_data = drop_data.drop(['A_Name','B_Name','S_ID','S_Name'],axis = 1)

In [210]:
ReDrop_data[drop_data['A_ID']!=drop_data['B_ID']].head()

,Product,TOrK,T_time,S_time,Payment,Reward,A_ID,A_gender,A_BD,B_ID,B_gender,B_BD,A_B_Relation_Ship
22,P610000000163,T,2018-05-17,2017-05-17,360.0,2481000,#,M,1899-12-31 00:00:00.000,610104201606063424,F,2016-06-06 00:00:00,P
24,P610000000376,T,2018-05-25,2017-05-25,100.0,694500,610121197609082214,M,1976-09-08 00:00:00,61012120001228220X,F,2000-12-28 00:00:00,C
38,P610000000387,T,2018-06-19,2017-06-19,110.0,110000,610104198108074433,M,1981-08-07 00:00:00,610104200810264421,F,2008-10-26 00:00:00,C
39,P610000000387,T,2018-06-19,2017-06-19,110.0,110000,61010319850522163X,M,1985-05-22 00:00:00,610104201305234445,F,2013-05-23 00:00:00,C
40,P610000000374,T,2018-06-27,2017-06-27,50.0,41000,620302197606120821,F,1976-06-12 00:00:00,610113200204281623,F,2002-04-28 00:00:00,C

In [211]:
#去掉身份证不完整的A人
ReDrop_data= ReDrop_data[ReDrop_data["A_ID"].map(len)==18]
#去掉身份证不完整的B人
test = ReDrop_data.B_ID.str.isnumeric()
test = list(test.dropna().index)
ReDrop_data = ReDrop_data.loc[test]
ReDrop_data = ReDrop_data[ReDrop_data["B_ID"].map(len)==18]
#生成A的年龄信息
ReDrop_data['A_age'] =  2019 - ReDrop_data.A_BD.dt.year
#生成B的年龄信息
ReDrop_data['B_age'] =  2019 - ReDrop_data.B_BD.dt.year
#去掉年龄是119的人
ReDrop_data = ReDrop_data[ReDrop_data['A_age'] < 119 ]

In [212]:
#年龄差
ReDrop_data['gap'] = ReDrop_data['A_age']-ReDrop_data['B_age']

In [213]:
#是否是给自己买的
t1 = list(ReDrop_data[ReDrop_data['A_ID']!=ReDrop_data['B_ID']].index)
t2 = list(ReDrop_data[ReDrop_data['A_ID']==ReDrop_data['B_ID']].index)
ReDrop_data.loc[t1,"forSelf"] = 0
ReDrop_data.loc[t2,"forSelf"] = 1

In [214]:
#是否是陕西
temp = ReDrop_data["A_ID"]
shanxi = []
notShanxi = []
for i in temp.index:
    if temp[i][0:2] != "61":
        notShanxi.append(i)
    else:
        shanxi.append(i)
ReDrop_data.loc[notShanxi,"shanxi"] = 0 # 0 表示不在陕西的人
ReDrop_data.loc[shanxi,"shanxi"] = 1 # 1 表示陕西人

In [215]:
#增加attribute 年龄gap 0 无年龄gap 
#1 表示投保人比受益人大 
#2 表示投保人比受益人小

ReDrop_data.loc[ReDrop_data[ReDrop_data["forSelf"] == 1].index,"gap_Level"] = 0

In [216]:
temp2 = ReDrop_data[ReDrop_data["forSelf"] != 1]["gap"] #所有投保人就是自己的人
overGap = []
lowGap = []
for i in temp2.index:
    if temp2[i] > 0:
        overGap.append(i)
    else:
        lowGap.append(i)
ReDrop_data.loc[overGap,"gap_Level"] = 1
ReDrop_data.loc[lowGap,"gap_Level"]= 2

In [220]:
ReDrop_data.loc[lowGap].head()

,Product,TOrK,T_time,S_time,Payment,Reward,A_ID,A_gender,A_BD,B_ID,B_gender,B_BD,A_B_Relation_Ship,A_age,B_age,gap,forSelf,shanxi,gap_Level
277,P610000000163,T,2018-07-19,2017-07-19,360.0,2481000,610122199701110340,F,1997-01-11 00:00:00,610528198905286052,M,1989-05-28 00:00:00,S,22,30,-8,0.0,1.0,2.0
389,P610100000455,T,2018-08-30,2017-08-30,100.0,55000,612429197404194641,F,1974-04-19 00:00:00,612429194305294264,F,1943-05-29 00:00:00,P,45,76,-31,0.0,1.0,2.0
438,P610100000455,T,2018-09-01,2017-09-01,100.0,55000,130406198005190313,M,1980-05-19 00:00:00,130406194402160312,M,1944-02-16 00:00:00,P,39,75,-36,0.0,0.0,2.0
441,P610100000455,T,2018-09-02,2017-09-02,100.0,55000,610121197108220025,F,1971-08-22 00:00:00,610121194902090068,F,1949-02-09 00:00:00,P,48,70,-22,0.0,1.0,2.0
442,P610100000455,T,2018-09-02,2017-09-02,100.0,55000,610103198007190455,M,1980-07-19 00:00:00,610112194906160039,M,1949-06-16 00:00:00,P,39,70,-31,0.0,1.0,2.0

In [219]:
ReDrop_data.loc[overGap].head()

,Product,TOrK,T_time,S_time,Payment,Reward,A_ID,A_gender,A_BD,B_ID,B_gender,B_BD,A_B_Relation_Ship,A_age,B_age,gap,forSelf,shanxi,gap_Level
24,P610000000376,T,2018-05-25,2017-05-25,100.0,694500,610121197609082214,M,1976-09-08 00:00:00,61012120001228220X,F,2000-12-28 00:00:00,C,43,19,24,0.0,1.0,1.0
38,P610000000387,T,2018-06-19,2017-06-19,110.0,110000,610104198108074433,M,1981-08-07 00:00:00,610104200810264421,F,2008-10-26 00:00:00,C,38,11,27,0.0,1.0,1.0
39,P610000000387,T,2018-06-19,2017-06-19,110.0,110000,61010319850522163X,M,1985-05-22 00:00:00,610104201305234445,F,2013-05-23 00:00:00,C,34,6,28,0.0,1.0,1.0
40,P610000000374,T,2018-06-27,2017-06-27,50.0,41000,620302197606120821,F,1976-06-12 00:00:00,610113200204281623,F,2002-04-28 00:00:00,C,43,17,26,0.0,0.0,1.0
41,P610000000387,T,2018-06-28,2017-06-28,110.0,110000,622827199006114925,F,1990-06-11 00:00:00,621027201211190316,M,2012-11-19 00:00:00,C,29,7,22,0.0,0.0,1.0

In [223]:
ReDrop_data.to_csv("newData.csv")